stages:
  prepare:
    cmd: python .\src\steps\prepare.py
    deps:
    - .\src\data\covid
    - .\src\steps\prepare.py
    params:
    - prepare.trainNum
    - prepare.dataset
    outs:
    - .\src\data\covid_dataset.json
  train:
    cmd: python -m src.steps.train
    deps:
    - .\src\data\covid
    - .\src\steps\train.py
    - .\src\data\covid_dataset.json
    params:
    - train.config
    - train.roi_size_w
    - train.roi_size_h
    - train.lr
    - train.batch_size
    - prepare.dataset
    outs:
    - .\src\weights\latest_weight.ckpt
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
artifacts:
  best:
    path: dvclive/artifacts/epoch=19-step=340-v1.ckpt
    type: model
