name: CI Tests Pipeline

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov ruff
      - name: Test with pytest
        run: |
          pytest --cov=. --cov-report xml
      - name: Make Badge
        uses: action-badges/cobertura-coverage-xml-badges@0.3.1
        with:
          file-name: coverage.svg
          badge-branch: badges
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          coverage-file-name: ./coverage.xml
